config/routes.rb
Rails.application.routes.draw do
  resources :tournaments
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :problems do
    resources :test_cases
  end
  resources :solutions do
    get "tests/update", on: :member, to: "solutions/tests#update", format: :js
  end
  devise_for :users
  get 'home/index'
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/problem.rb
class Problem < ApplicationRecord
  has_many :users
  has_many :test_cases, dependent: :destroy
  has_many :solutions, dependent: :destroy
  belongs_to :tournament, optional: true

  validates :title, presence: true
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  load_and_authorize_resource

  # GET /problems
  def index
  end

  # GET /problems/1
  def show
    @problem_solution = Solution.find_by(problem: @problem, user: current_user)
  end

  # GET /problems/new
  def new
  end

  # GET /problems/1/edit
  def edit
  end

  # POST /problems
  def create
    if @problem.save
      redirect_to @problem, notice: 'Problem was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /problems/1
  def update
    if @problem.update(problem_params)
      redirect_to @problem, notice: 'Problem was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /problems/1
  def destroy
    @problem.destroy
    redirect_to problems_url, notice: 'Problem was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def problem_params
      params.require(:problem).permit(:title, :description, :tournament_id)
    end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_card.html.erb
<div class="card">
  <div class="card-content">
    <strong><%= link_to problem.title, problem, class: "black-text" %><strong>
  </div>
  <div class="card-tabs">
    <ul class="tabs tabs-fixed-width">
      <% problem.test_cases.each_with_index do |test_case, i| %>
        <li class="tab">
          <a 
          <% if i == 0 %>
            class="active" 
          <% end %>
          href="#problem_<%= problem.id %>_test_case_<%= i %>">
          Test #<%= i %>
          </a>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="card-content grey lighten-4">
    <% problem.test_cases.each_with_index do |test_case, i| %>
      <div id="problem_<%= problem.id %>_test_case_<%= i %>"><%= test_case.input %> => <%= test_case.output %></div>
    <% end %>
  </div>
  <% if can? :edit, problem %>
    <div class="card-action">
      <%= link_to 'Edit', edit_problem_path(problem), class: "btn orange" %>
      <%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-pirate-red" %>
    </div>
  <% end %>
</div>

app/views/problems/_form.html.erb
<%= simple_form_for(@problem) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.association :tournament %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/problems/_table.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <% if can? :create, Problem %>
        <th colspan="3"></th>
      <% else %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% problems.each do |problem| %>
      <tr>
        <td><%= problem.title %></td>
          <td><%= link_to 'Show', problem %></td>
        <% if can? :edit, @problem %>
          <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
          <td><%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/problems/edit.html.erb
<h1>Editing Problem</h1>

<%= render 'form', problem: @problem %>
<div class="small-br"></div>
<%= link_to 'Show', @problem, class: "btn btn-pirate-skyblue"  %>
<%= link_to 'Back', problems_path, class: "btn btn-pirate-skyblue"  %>

app/views/problems/index.html.erb
<h1>Problems</h1>

<div class="row">
  <% @problems.each do |problem| %>
    <div class="col s12 m6 xl4">
      <%= render "card", problem: problem %>
    </div>
  <% end %>
</div>

<br>

<% if can? :create, Problem %>
  <div class="fixed-action-btn vertical">
    <%= link_to new_problem_path, class: 'btn-floating btn-large green' do %>
      <i class="large material-icons"> add </i>
    <% end %>
  </div>
<% end %>

app/views/problems/new.html.erb
<h1>New Problem</h1>

<%= render 'form', problem: @problem %>

app/views/problems/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @problem.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @problem.description %>  
</p>

<h2>Test cases</h2>
<%= render "test_cases/table", test_cases: @problem.test_cases %>

<br>
<% if @problem_solution %>
  <%= link_to "Your Solution", solution_path(@problem_solution), class: "btn btn-pirate-skyblue" %>
<% elsif current_user %>
  <%= simple_form_for(Solution.new) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <%= f.hidden_field :problem_id, value: @problem.id, class: "hidden" %>
    <%= f.button :submit %>
  <% end %>
<% else %>
  Sign up/in to make a solution!
<% end %>

<% if can? :edit, @problem %>
  <div class="fixed-action-btn vertical">
    <%= link_to edit_problem_path(@problem), class: 'btn-floating btn-large btn-pirate-red' do %>
      <i class="large material-icons"> mode_edit </i>
    <% end %>
    <ul>
      <li>
        <%= link_to new_problem_test_case_path(@problem), class: "btn-floating green" do %>
          <i class="material-icons"> add </i>
        <% end %>
      </li>
    </ul>
  </div>
<% end %>