config/routes.rb
Rails.application.routes.draw do
  resources :tournaments
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :problems do
    resources :test_cases
  end
  resources :solutions do
    get "tests/update", on: :member, to: "solutions/tests#update", format: :js
  end
  devise_for :users
  get 'home/index'
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :problems

  validates :title, presence: true
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  load_and_authorize_resource

  # GET /tournaments
  def index
  end

  # GET /tournaments/1
  def show
  end

  # GET /tournaments/new
  def new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  def create
    if @tournament.save
      redirect_to @tournament, notice: 'Tournament was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tournaments/1
  def update
    if @tournament.update(tournament_params)
      redirect_to @tournament, notice: 'Tournament was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tournaments/1
  def destroy
    @tournament.destroy
    redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.'
  end

  private

    # Only allow a trusted parameter "white list" through.
    def tournament_params
      params.require(:tournament).permit(:title, :description, :start_at, :end_at)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= simple_form_for(@tournament) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :start_at %>
    <%= f.input :end_at %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'form', tournament: @tournament %>
<div class="small-br"></div>
<%= link_to 'Show', @tournament, class: "btn btn-pirate-skyblue" %>

app/views/tournaments/index.html.erb
<h1>Tournaments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start at</th>
      <th>End at</th>
      <% if can? :create, Tournament %>
        <th colspan="3"></th>
      <% else %>
        <th></th>  
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= tournament.title %></td>
        <td><%= tournament.start_at %></td>
        <td><%= tournament.end_at %></td>
        <td><%= link_to 'Show', tournament %></td>
        <% if can? :edit, tournament %>
          <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
          <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Tournament %>
  <div class="fixed-action-btn vertical">
    <%= link_to new_tournament_path, class: 'btn-floating btn-large green' do %>
      <i class="large material-icons"> add </i>
    <% end %>
  </div>
<% end %>

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>

<%= render 'form', tournament: @tournament %>

app/views/tournaments/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @tournament.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tournament.description %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @tournament.start_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @tournament.end_at %>
</p>

<h1>Problems</h1>
<%= render "problems/table", problems: @tournament.problems %>

<% if can? :edit, @tournament %>
  <div class="fixed-action-btn vertical">
    <%= link_to edit_tournament_path(@tournament), class: 'btn-floating btn-large btn-pirate-red' do %>
      <i class="large material-icons"> mode_edit </i>
    <% end %>
  </div>
<% end %>