config/routes.rb
Rails.application.routes.draw do
  resources :tournaments
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :problems do
    resources :test_cases
  end
  resources :solutions do
    get "tests/update", on: :member, to: "solutions/tests#update", format: :js
  end
  devise_for :users
  get 'home/index'
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="flash flash-<%= type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<div class="navbar-fixed">
  <nav class="pirate-red-bg nav-extended">
    <div class="container">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo white-text">
          Code Champion
        </a>
        <div class="right">
          <a href="#" class="button-collapse hide-on-large-and-up" data-activates="mobile-menu">
            <i class="material-icons"> menu </i>
          </a>
        </div>
        <ul class="right hide-on-med-and-down">
          <%= render partial: "shared/menu_items" %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_menu_items.html.erb
<li>
  <%= link_to 'Problems', problems_path, class: 'white-text' %>
</li>

<li>
  <%= link_to 'Solutions', solutions_path, class: 'white-text' %>
</li>

<li>
  <%= link_to 'Tournaments', tournaments_path, class: 'white-text' %>
</li>

<li>
  <% if current_user %>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'white-text' %>
  <% else %>
    <%= link_to 'Sign in', new_user_session_path, class: 'white-text' %>
  <% end %>
</li>

app/views/shared/flash.html.erb
<% flash.each do |type, message| %>
  <div class="flash flash-<%= type %>">
    <%= message %>
  </div>
<% end %>