config/routes.rb
Rails.application.routes.draw do
  resources :tournaments
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :problems do
    resources :test_cases
  end
  resources :solutions do
    get "tests/update", on: :member, to: "solutions/tests#update", format: :js
  end
  devise_for :users
  get 'home/index'
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/solution.rb
class Solution < ApplicationRecord
  DEFAULT_BLOCK_XML = "<xml xmlns=\"https://developers.google.com/blockly/xml\"><variables><variable id=\"M]7C3TsKJ3bRAX`ne-7:\">output</variable><variable id=\"^Vp(/O1bTevV}H^ieaSB\">input</variable></variables><block type=\"variables_set\" id=\"Ua!|:nI}|a#M.#kH$05.\" x=\"29\" y=\"61\"><field name=\"VAR\" id=\"M]7C3TsKJ3bRAX`ne-7:\">output</field><value name=\"VALUE\"><block type=\"variables_get\" id=\"}/r2FVe*nER`rpbf=~nu\"><field name=\"VAR\" id=\"^Vp(/O1bTevV}H^ieaSB\">input</field></block></value></block></xml>"
  belongs_to :problem
  belongs_to :user
  belongs_to :language
  has_many :test_case_solutions, dependent: :destroy

  after_create :create_test_case_solutions

  def run_tests
    test_case_solutions.each(&:run_test)
  end

  def test_status
    return "untested".freeze if test_case_solutions.map(&:status).include?("untested")
    return "failing".freeze if test_case_solutions.map(&:status).include?("failing")
    "passing".freeze
  end

  private
    def create_test_case_solutions
      problem.test_cases.each do |test_case|
        TestCaseSolution.create(
          solution: self,
          status: :untested,
          test_case: test_case
        )
      end
    end
end

app/controllers/solutions/tests_controller.rb
class Solutions::TestsController < ApplicationController
  before_action :set_solution

  def update
    @solution.run_tests
  end

  private
    def set_solution
      @solution = Solution.find(params[:id])
    end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  load_and_authorize_resource

  # GET /solutions
  def index
  end

  # GET /solutions/1
  def show
  end

  # POST /solutions
  def create
    @solution.user = current_user
    @solution.language = Language.first
    @solution.block_xml = Solution::DEFAULT_BLOCK_XML
    if @solution.save
      redirect_to @solution, notice: 'Solution was successfully created.'
    else
      redirect_to @solution.problem, notice: @solution.errors.messages
    end
  end

  # PATCH/PUT /solutions/1
  def update
    if @solution.update(solution_params)
      redirect_to @solution, notice: 'Solution was successfully updated.'
    else
      render :show
    end
  end

  # DELETE /solutions/1
  def destroy
    @solution.destroy
    redirect_to solutions_url, notice: 'Solution was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def solution_params
      params.require(:solution).permit(:problem_id, :code, :language_id, :block_editor, :block_xml)
    end
end

app/helpers/solutions/tests_helper.rb
module Solutions::TestsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/solutions/_block_editor.html.erb
<div id="blocklyDiv" style="height: 480px; width: 100%;"></div>

<xml xmlns="https://developers.google.com/blockly/xml" id="toolbox" style="display: none">
    <category name="Logik" colour="%{BKY_LOGIC_HUE}">
      <block type="controls_if"></block>
      <block type="logic_compare"></block>
      <block type="logic_operation"></block>
      <block type="logic_negate"></block>
      <block type="logic_boolean"></block>
      <block type="logic_null"></block>
      <block type="logic_ternary"></block>
    </category>
    <category name="Løkker" colour="%{BKY_LOOPS_HUE}">
      <block type="controls_repeat_ext">
        <value name="TIMES">
          <shadow type="math_number">
            <field name="NUM">10</field>
          </shadow>
        </value>
      </block>
      <block type="controls_whileUntil"></block>
      <block type="controls_for">
        <value name="FROM">
          <shadow type="math_number">
            <field name="NUM">1</field>
          </shadow>
        </value>
        <value name="TO">
          <shadow type="math_number">
            <field name="NUM">10</field>
          </shadow>
        </value>
        <value name="BY">
          <shadow type="math_number">
            <field name="NUM">1</field>
          </shadow>
        </value>
      </block>
      <block type="controls_forEach"></block>
      <block type="controls_flow_statements"></block>
    </category>
    <category name="Matematik" colour="%{BKY_MATH_HUE}">
      <block type="math_number">
        <field name="NUM">123</field>
      </block>
      <block type="math_arithmetic">
        <value name="A">
          <shadow type="math_number">
            <field name="NUM">1</field>
          </shadow>
        </value>
        <value name="B">
          <shadow type="math_number">
            <field name="NUM">1</field>
          </shadow>
        </value>
      </block>
      <block type="math_single">
        <value name="NUM">
          <shadow type="math_number">
            <field name="NUM">9</field>
          </shadow>
        </value>
      </block>
      <block type="math_trig">
        <value name="NUM">
          <shadow type="math_number">
            <field name="NUM">45</field>
          </shadow>
        </value>
      </block>
      <block type="math_constant"></block>
      <block type="math_number_property">
        <value name="NUMBER_TO_CHECK">
          <shadow type="math_number">
            <field name="NUM">0</field>
          </shadow>
        </value>
      </block>
      <block type="math_round">
        <value name="NUM">
          <shadow type="math_number">
            <field name="NUM">3.1</field>
          </shadow>
        </value>
      </block>
      <block type="math_on_list"></block>
      <block type="math_modulo">
        <value name="DIVIDEND">
          <shadow type="math_number">
            <field name="NUM">64</field>
          </shadow>
        </value>
        <value name="DIVISOR">
          <shadow type="math_number">
            <field name="NUM">10</field>
          </shadow>
        </value>
      </block>
      <block type="math_constrain">
        <value name="VALUE">
          <shadow type="math_number">
            <field name="NUM">50</field>
          </shadow>
        </value>
        <value name="LOW">
          <shadow type="math_number">
            <field name="NUM">1</field>
          </shadow>
        </value>
        <value name="HIGH">
          <shadow type="math_number">
            <field name="NUM">100</field>
          </shadow>
        </value>
      </block>
      <block type="math_random_int">
        <value name="FROM">
          <shadow type="math_number">
            <field name="NUM">1</field>
          </shadow>
        </value>
        <value name="TO">
          <shadow type="math_number">
            <field name="NUM">100</field>
          </shadow>
        </value>
      </block>
      <block type="math_random_float"></block>
      <block type="math_atan2">
        <value name="X">
          <shadow type="math_number">
            <field name="NUM">1</field>
          </shadow>
        </value>
        <value name="Y">
          <shadow type="math_number">
            <field name="NUM">1</field>
          </shadow>
        </value>
      </block>
    </category>
    <category name="Tekst" colour="%{BKY_TEXTS_HUE}">
      <block type="text"></block>
      <block type="text_join"></block>
      <block type="text_append">
        <value name="TEXT">
          <shadow type="text"></shadow>
        </value>
      </block>
      <block type="text_length">
        <value name="VALUE">
          <shadow type="text">
            <field name="TEXT">abc</field>
          </shadow>
        </value>
      </block>
      <block type="text_isEmpty">
        <value name="VALUE">
          <shadow type="text">
            <field name="TEXT"></field>
          </shadow>
        </value>
      </block>
      <block type="text_indexOf">
        <value name="VALUE">
          <block type="variables_get">
            <field name="VAR">{textVariable}</field>
          </block>
        </value>
        <value name="FIND">
          <shadow type="text">
            <field name="TEXT">abc</field>
          </shadow>
        </value>
      </block>
      <block type="text_charAt">
        <value name="VALUE">
          <block type="variables_get">
            <field name="VAR">{textVariable}</field>
          </block>
        </value>
      </block>
      <block type="text_getSubstring">
        <value name="STRING">
          <block type="variables_get">
            <field name="VAR">{textVariable}</field>
          </block>
        </value>
      </block>
      <block type="text_changeCase">
        <value name="TEXT">
          <shadow type="text">
            <field name="TEXT">abc</field>
          </shadow>
        </value>
      </block>
      <block type="text_trim">
        <value name="TEXT">
          <shadow type="text">
            <field name="TEXT">abc</field>
          </shadow>
        </value>
      </block>
      <block type="text_print">
        <value name="TEXT">
          <shadow type="text">
            <field name="TEXT">abc</field>
          </shadow>
        </value>
      </block>
      <block type="text_prompt_ext">
        <value name="TEXT">
          <shadow type="text">
            <field name="TEXT">abc</field>
          </shadow>
        </value>
      </block>
    </category>
    <category name="Lister" colour="%{BKY_LISTS_HUE}">
      <block type="lists_create_with">
        <mutation items="0"></mutation>
      </block>
      <block type="lists_create_with"></block>
      <block type="lists_repeat">
        <value name="NUM">
          <shadow type="math_number">
            <field name="NUM">5</field>
          </shadow>
        </value>
      </block>
      <block type="lists_length"></block>
      <block type="lists_isEmpty"></block>
      <block type="lists_indexOf">
        <value name="VALUE">
          <block type="variables_get">
            <field name="VAR">{listVariable}</field>
          </block>
        </value>
      </block>
      <block type="lists_getIndex">
        <value name="VALUE">
          <block type="variables_get">
            <field name="VAR">{listVariable}</field>
          </block>
        </value>
      </block>
      <block type="lists_setIndex">
        <value name="LIST">
          <block type="variables_get">
            <field name="VAR">{listVariable}</field>
          </block>
        </value>
      </block>
      <block type="lists_getSublist">
        <value name="LIST">
          <block type="variables_get">
            <field name="VAR">{listVariable}</field>
          </block>
        </value>
      </block>
      <block type="lists_split">
        <value name="DELIM">
          <shadow type="text">
            <field name="TEXT">,</field>
          </shadow>
        </value>
      </block>
      <block type="lists_sort"></block>
    </category>
    <category name="Variabler" colour="%{BKY_VARIABLES_HUE}" custom="VARIABLE"></category>
    <category name="Funktioner" colour="%{BKY_PROCEDURES_HUE}" custom="PROCEDURE"></category>
  </xml>

<xml xmlns="https://developers.google.com/blockly/xml" id="startBlocks" style="display: none">
  <block type="controls_if" inline="false" x="20" y="20">
    <mutation else="1"></mutation>
    <value name="IF0">
      <block type="logic_compare" inline="true">
        <field name="OP">EQ</field>
        <value name="A">
          <block type="math_arithmetic" inline="true">
            <field name="OP">MULTIPLY</field>
            <value name="A">
              <block type="math_number">
                <field name="NUM">6</field>
              </block>
            </value>
            <value name="B">
              <block type="math_number">
                <field name="NUM">7</field>
              </block>
            </value>
          </block>
        </value>
        <value name="B">
          <block type="math_number">
            <field name="NUM">42</field>
          </block>
        </value>
      </block>
    </value>
    <statement name="DO0">
      <block type="text_print" inline="false">
        <value name="TEXT">
          <block type="text">
            <field name="TEXT">Don't panic</field>
          </block>
        </value>
      </block>
    </statement>
    <statement name="ELSE">
      <block type="text_print" inline="false">
        <value name="TEXT">
          <block type="text">
            <field name="TEXT">Panic</field>
          </block>
        </value>
      </block>
    </statement>
  </block>
</xml>

app/views/solutions/_test_case_solutions.html.erb
<div class="row">
  <% @solution.test_case_solutions.each_with_index do |test_case_solution, i| %>
    <div class="col s4">
      <div class="card">
        <div class="card-content white-text <%= test_case_solution.status == 'failing' ? 'red' : 'green' %>">
          <strong>
            Test #<%= i %> - <%= test_case_solution.status %>
          </strong>
        </div>
        <div class="card-content">
          <table class="table">
            <tbody>
              <tr><td><strong>Input</strong></td><td><%= test_case_solution.test_case.input %></td></tr>
              <tr><td><strong>Expected Output</strong></td><td><%= test_case_solution.test_case.output %></td></tr>
              <tr><td><strong>Actual Output</strong></td><td><%= test_case_solution.output %></td></tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/solutions/index.html.erb
<h1>My Solutions</h1>

<table>
  <thead>
    <tr>
      <th>Problem</th>
      <th>Test Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solutions.each do |solution| %>
      <tr>
        <td><%= solution.problem.title %></td>
        <td><%= solution.test_status %></td>
        <td><%= link_to 'Show', solution %></td>
        <td><%= link_to 'Edit', edit_solution_path(solution) %></td>
        <td><%= link_to 'Destroy', solution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/solutions/show.html.erb
<h1>
  <%= link_to "#{@solution.problem.title}", problem_path(@solution.problem), class: "black-text" %>
</h1>
<p>
  <%= @solution.problem.description %>
</p>

<pre id="code-editor" class="code-editor">
  <% if @solution.code.blank? %>
#Parse the input variable and return a new result
#puts input
  <% else %>
<%= @solution.code %>
  <% end %>
</pre>

<% if @solution.block_editor? %>
  <%= render "block_editor" %>
<% end %>

<%= simple_form_for(@solution) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.hidden_field :code %>
  <%= f.association :language, include_blank: false %>
  <%= f.input :block_editor %>
  <%= f.hidden_field :block_xml %>
  <% if can? :update, @solution %>
    <div class="fixed-action-btn vertical">
      <button type="submit" class= "btn-floating btn-large btn-pirate-skyblue">
        <i class="large material-icons"> save </i>
      </button>
    </div>
  <% end %>
<% end %>

<%= link_to "Run Tests", tests_update_solution_path(@solution), class: 'btn btn-pirate-skyblue', remote: true %>

<div id="test_case_solutions">
  <%= render "test_case_solutions" %>
</div>